### ISSUE TITLE
Import external library

### ISSUE THREAD

**Issue by cedricguillou** [jupyter-widgets/widget-cookiecutter#17]
Hi!

I'm trying to build a custom ipywidget based on an external library, and I'm wondering what is the best way to import and use this library (one .JS file + one CSS file)? For information, this library has to be installed manually (no npm package).

Thx!
Best regards

Cédric

**Comment by Nic30** [comment]
How is your js/css library distributed? The best way is to create a npm package for it and than add it in dependencies as usual.
