### ISSUE TITLE
Development workflow?

### ISSUE THREAD

**Issue by akloster** [jupyter-widgets/widget-cookiecutter#22]
The documentation doesn't tell me how to make changes I made to the javascript part of a widget visible in the browser. I figured it out, but it is contraintuitive: I have to run "npm run prepublish". I may even figure out how to recompile the js automatically.

Is that the recommended way?

Also, these widgets seem to be a jupyter extension, which has to be installed and enabled in the user's profile. For all sorts of reasons I don't like that.

Now everything javascript/css related will depend on what the user has installed in his profile, instead of the library installed in his environment. It also requires an additional installation step for anyone interested in using a library which comes with jupyter widgets.

In my personal opinion, I prefer styling and javascript to come from the notebook and the libraries it imports, not the user's jupyter profile. This was especially helpful for managing presentations.

I assume there are other ways of doing things, and I suspect that the way of using npm and extensions is particular to this widget template, which is why I am submitting this issue in this repository rather than with ipywidgets or jupyter.

**Comment by jasongrout** [comment]
> The documentation doesn't tell me how to make changes I made to the javascript part of a widget visible in the browser. I figured it out, but it is contraintuitive: I have to run "npm run prepublish". I may even figure out how to recompile the js automatically.
> 
> Is that the recommended way?

We should put a few more commands in, like `npm run watch` to recompile the javascript automatically and `npm run build` to build the js.

> Also, these widgets seem to be a jupyter extension, which has to be installed and enabled in the user's profile. 

Yes, things that use the jupyter widgets infrastructure are distributed as notebook extensions. However, we strongly encourage (especially when using virtual or conda environments) to install these at the sys-prefix level, not the user home directory level. The installation is done automatically at the sys-prefix level when the package is installed, but it still does require the user to run a command to enable the extension (again, at the sys-prefix level). There is some preliminary work to rewrite the Jupyter notebook server to have a different extension architecture that will allow things to work without this separate `nbextension enable` step.

**Comment by jasongrout** [comment]
> The documentation doesn't tell me how to ... 

We definitely welcome pull requests to make the documentation or cookie cutter better. For example, it also needs to be updated to ipywidgets 7.0 beta.

**Comment by akloster** [comment]
Doesn't installing in the sys-prefix level make an extension only available for the environment running the jupyter server, instead of the kernel? For example if I have two environments, one called py27 and one called py36, and I install an extension from any one of them, and then use the other environment as a kernel, I would have to make sure that they have compatible javascript/css files, right?

Then again, with jupyterlab all open notebooks may have their javascript assets clashing anyway.

I'm probably not yet seeing the whole picture clearly.

**Comment by jasongrout** [comment]
I would do it this way:

Install widgetsnbextension in the same environment that your Jupyter server runs from. Enable the nbextension there.

Install ipywidgets in each kernel environment you are running.

You're right that you should make sure that the ipywidgets and widgetsnbextension versions are compatible.

**Comment by vidartf** [comment]
Closing as answered. If any issues remain, they should probably be opened as individual issues
