### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by pluradj** [jupyter-widgets/widget-cookiecutter#25]
This project is missing the BSD-3 license.

**Comment by SylvainCorlay** [comment]
Actually, I think that the cookiecutter should probably be CC-0 since it is example code.

**Comment by jokalokao** [comment]
So, does this package have an actual license? I need to know due to a project I'm working on.

**Comment by deeplook** [comment]
Any update here?  I work in a place that will refuse to even consider a package without an explicit license...

**Comment by vidartf** [comment]
I merged the license in https://github.com/jupyter-widgets/widget-cookiecutter/pull/26, but a more permissive license is probably acceptable if someone wants to do a PR changeing it to e.g. CC-0 as outlined in that discussion.
