### ISSUE TITLE
build a package not using npm

### ISSUE THREAD

**Issue by achapkowski** [jupyter-widgets/widget-cookiecutter#30]
Can you build the package not using npm for the JS code?
Everytime I need to change something, I have to do the following:

1. Increase the package number
2. rebuild everything 

If I am accessing a JS file hosted by a company, say google, why do I need to bundle it?  Is there a way to prevent that from happening?  Is there a way to test this locally without doing the who npm -> build -> publish to hosting site process?

**Comment by vidartf** [comment]
You don't have to bundle it, that is just the most common scenario that people would want. Publishing to npm is useful e.g. if you want other to be able to depend on the code, install it as a a lab extension, or use it with the HTML manager (which fetches the code from unpkg).

Closing as answered, but feel free to comment further if needed 👍
