### ISSUE TITLE
Syntax error in labplugin.js if npm_package_name contains hyphens

### ISSUE THREAD

**Issue by zakandrewking** [jupyter-widgets/widget-cookiecutter#39]
JavaScript variables cannot contain hyphens, so this syntax is invalid when `npm_package_name` contains hyphens (e.g. with the default value `"jupyter-widget-example"`):

https://github.com/jupyter-widgets/widget-cookiecutter/blob/0aa620eaa2b4365ccfc755eb2a9262e2f6bed974/%7B%7Bcookiecutter.github_project_name%7D%7D/js/lib/labplugin.js#L1

**Comment by vidartf** [comment]
I don't think this variable need to equal to the package name. A static name should suffice, if someone wants to submit a PR.

**Comment by vidartf** [comment]
Actually, this seems to be fixed in master.
