### ISSUE TITLE
custom widget works locally but does not embed

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/widget-cookiecutter#40]
I'm trying to figure out how to get widget embedding working using the [widget-ts-cookiecutter](https://github.com/jupyter-widgets/widget-ts-cookiecutter) (I raised the issue [here](https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/29)). I tried re-building my widget [here](https://github.com/ismms-himc/clustergrammer2) using this non TypeScript cookiecutter. 

The widget embedding is working when I render the notebook suing NBViewer ([link](http://nbviewer.jupyter.org/github/ismms-himc/clustergrammer2/blob/master/Running_Clustergrammer2.ipynb)), but the embedding is not working when I try and view within a HTML file (saved using the Download as HTML option) [link to HTML file](https://github.com/ismms-himc/clustergrammer2/tree/master/html_notebooks). I see the following errors in the console of the HTML file: 

<img width="771" alt="screen shot 2018-08-31 at 1 52 46 am" src="https://user-images.githubusercontent.com/8352840/44895215-5df80100-acc1-11e8-928b-9d3e1f9fa938.png">

My goal is to get the TypeScript version to be embeddable since it already supports Jupyter Lab and works in MyBinder.

**Comment by cornhundred** [comment]
I can verify that the widget works in mybinder: see [Running_Clustergrammer2 notebook](https://mybinder.org/v2/gh/ismms-himc/clustergrammer2/master?filepath=Running_Clustergrammer2.ipynb) and the widget built from the widget-ts-cookiecutter also works in mybinder, see [introduction notebook](https://mybinder.org/v2/gh/ismms-himc/clustergrammer_widget2/master?filepath=examples%2Fintroduction.ipynb) - which is great! However, this widget does not work in Jupyter Lab. 

I'm still working on understanding the embedding process using the [docs](https://ipywidgets.readthedocs.io/en/stable/embedding.html?highlight=embed) and comparing the different widgets I've made using these cookiecutters. The [Migrating custom widget libraries](https://ipywidgets.readthedocs.io/en/stable/migration_guides.html?highlight=embed) documentation looks relevant. 

@maartenbreddels and @jasongrout if you have any ideas on how to best proceed with fixing embedding I would greatly appreciate it. Cheers

**Comment by cornhundred** [comment]
The embedding issue was caused by nbconvert, running the latest un-released nbconvert on the terminal correctly generates an HTML with an embedded widget ([link](https://github.com/ismms-himc/clustergrammer2/blob/master/Running_Clustergrammer2_nbconvert.html)). This was the same [issue](https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/29) I raised in the widget-ts-cookiecutter repo.

**Comment by vidartf** [comment]
Thanks for posting back after you found the solution!
