### ISSUE TITLE
Updating js requires browser refresh

### ISSUE THREAD

**Issue by dlarendt** [jupyter-widgets/widget-cookiecutter#42]
I am following the instructions for working in the development environment. Everything seems to be linked correctly. However, if I make a change to example.js and `npm run prepublish`, this change is not visible in the jupyter notebook until I refresh the entire page. I would expect to see the updated widget when I re-run the cell containing the widget. Restarting the kernel also still shows the old version of the widget.

How do I get the updated js in the widget loaded into the browser without refreshing the page?

**Comment by vidartf** [comment]
It is not possible out of the box, as the browser will not ask again for the JS every time it uses the code. There are some development tools that do allow the server to push "hot module reloads" through, so you could try looking into this. Not sure about the difficulty level of this one though.

**Comment by vidartf** [comment]
Closing as answered, feel free to comment if anyone finds a good practical solution here.
