### ISSUE TITLE
Add description of each javascript file to README

### ISSUE THREAD

**Issue by djhoese** [jupyter-widgets/widget-cookiecutter#48]
I could see this going in either a README or perhaps clearing up the js file's internal documentation. I created this after talking with @jasongrout on gitter, but the more I look at the files it may not be entirely necessary. I'm thinking I just didn't read the documentation that was already here. Keep in mind I am not well versed in javascript.

One example of something that is confusing is embed.js:

> Entry point for the unpkg bundle containing custom model definitions.

I think I know what that means based on what I learned about embedding widgets/extensions in general, but I'm really not sure.

Anyway, I'm wondering if it would be useful to have an overview in one of the README's describing each javascript file and what it does. In most cases someone following the template shouldn't have to care, but when things go wrong it may help a new contributor.

**Comment by vidartf** [comment]
It would probably be cleaner to put such an explanation in a separate file. TBH, if someone would make a PR with a skeleton for this (a list of all files currently generated, and a best guess as to what they are/do), it would be a lot easier to share the load between the different people in the know 👍

**Comment by pbugnion** [comment]
Thanks to @mbektasbbg (PR #57 ), we now have a filetree with basic explanations for each file in the README.

Feel free to create new issues if you think that's still incomplete (it probably is).
