### ISSUE TITLE
Documentation does not explain what do with the generated code. 

### ISSUE THREAD

**Issue by frankgerhardt** [jupyter-widgets/widget-cookiecutter#53]
Documentation does not explain what do with the generated code. 

Even the TS Cookiecutter https://github.com/jupyter-widgets/widget-ts-cookiecutter has more explanation in the README. If the cookie cutter is meant to make it easier to get started, then why not explain it better!?

**Comment by djhoese** [comment]
> If the cookie cutter is meant to make it easier to get started, then why not explain it better!?

I'm not a maintainer for this project so I'm not speaking for them, but if you have things that you think could be improved you can make a pull request to add the information you think is missing. Pull requests are always welcome on an open source project. If you don't know exactly what information needs to be added maybe in this issue you could describe what specific information you think is missing. What stage are you at in widget development and what else do you need to finish your project that this cookiecutter could provide. You point out that the ts cookiecutter has more information, what information specifically?

What you may see as obviously missing, others may not realize. Help them out.

**Comment by vidartf** [comment]
I agree that ideally there should be more documentation about how to write widget extensions in general (either in the ipywidget repo, or in the cookiecutters). Of course, the problem with writing documentation is that people will demand that you keep it up to date as well 😄

**Comment by pbugnion** [comment]
Thanks to @mbektasbbg , we now have much better documentation in the README (PR #57 ). I'm closing this for now, but feel free to open new specific issues if you think there is something missing.

As @djhoese said, maintainers will often not realise when key bits of information is missing.
