### ISSUE TITLE
Add entry in cookiecutter project README

### ISSUE THREAD

**Issue by willingc** [jupyter-widgets/widget-cookiecutter#6]
There's a section for Data Science in the cookiecutter project's README. We should add a link to this project there.

Great to see folks on the mailing list finding the widget-cookiecutter helpful.

**Comment by SylvainCorlay** [comment]
Another project than cookiecutter itself?

**Comment by willingc** [comment]
@SylvainCorlay I would suggest adding it here https://github.com/audreyr/cookiecutter/blob/master/README.rst#data-science

or create an IPython/Jupyter section.

**Comment by SylvainCorlay** [comment]
Gotcha, I am :+1: on this!

**Comment by hackebrot** [comment]
Hi 👋 

Looks like this can be closed. Thanks again for [the PR](https://github.com/audreyr/cookiecutter/pull/781) @willingc 😁

**Comment by willingc** [comment]
Hi hi @hackebrot. Closing here :-)
