### ISSUE TITLE
widget renders only after restart of the kernel

### ISSUE THREAD

**Issue by Nic30** [jupyter-widgets/widget-cookiecutter#60]
Hello,

I used this repo to generate a jupyter widget extension https://github.com/Nic30/jupyter_widget_hwt
It is working just fine, but I would like to ask if this behaviour is expected:

* If I open notebook for the first time I need to restart a kernel to render it
  otherwise I see only dummy text (see https://mybinder.org/v2/gh/Nic30/jupyter_widget_hwt.git/master?filepath=examples%2Fexample_simple.ipynb )

* The JS is not available in notebook itself which means that it does not work in noteboook preview on github (see https://github.com/Nic30/jupyter_widget_hwt/blob/master/examples/example_simple.ipynb)

* `jupyter nbextension enable --py widgetsnbextension` is incredibly slow, it takes several minutes, this is very unplesant when using mybinder to demostrate examples.

I made this extension to simplify the debugging process of some lib, but the current behaviour +  installation makes it even more complicated, is there any way how to solve mentioned issues?

I am new to Jupyter, I would be glad for any hint.

**Comment by Nic30** [comment]
> need to restart a kernel to render

* it is required to set [trusted=True](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html?highlight=trust#signing-notebooks)

**Comment by vidartf** [comment]
> `jupyter nbextension enable --py widgetsnbextension` is incredibly slow

If it was a `jupyter labextension install ...` step that would be expected as lab would need to install all its dependencies (cacheable) and repack its entire JS bundle. For `nbextension enable` it should just be flipping a value in a JSON file....

**Comment by Nic30** [comment]
@vidartf yes, `enable` triggers `install` in my case and npm based js recking is very slow and I am using `elk` which has around 4.5MB which makes situation even worse.

Also I found out that the examples for plotly and other widgets works in same way.
In order to render the widgets by default it is required to save notebook with state and make it trusted, all widgets have to be installed and enabled etc.

From my (user) point of view this is just additional complication which confuses potential visitors of my jupyter based examples.
I am not satisfied with current behavior but I do not think this is solvable on widget level, that is why I am closing this issue.
