### ISSUE TITLE
Does it Hot-Reload?

### ISSUE THREAD

**Issue by saraedum** [jupyter-widgets/widget-cookiecutter#63]
The README currently says that `jupyter lab --watch` allows me to hot-reload the extension. I understand "hot-reload" as in [Hot Module Replacement](https://webpack.js.org/guides/hot-module-replacement/), but it does not do that for me. It just rebuilds. That's fine but should we update the README to say that it "automatically rebuilds"?

Or am I doing something wrong and it should actually hot-reload?

**Comment by martinRenou** [comment]
> It just rebuilds

Yeah that's just what it does, JupyterLab needs to rebuild. Would you like to open a PR to update the README?

**Comment by saraedum** [comment]
Sure: https://github.com/jupyter-widgets/widget-cookiecutter/pull/64
