### ISSUE TITLE
What is the purpose of publishing to NPM?

### ISSUE THREAD

**Issue by sodennis** [jupyter-widgets/widget-cookiecutter#73]
I'm currently developing a Jupyter widget for embedding the Monaco Editor within Jupyter Notebook. I understand we want to publish our packages to pypi so that we can install the Python packages and use them within Jupyter. 

Currently looking at how the setup.py is configured, we bundle the JS static assets within the wheel package. At which point, do we pull the assets from NPM and not use the bundled assets? Why do we publish our JS assets to NPM in the first place?

**Comment by jasongrout** [comment]
> Why do we publish our JS assets to NPM in the first place?

Publishing to npm allows things like the html manager to get the js code to use the widget on plain html pages without a kernel, for example. It also allows other widgets to import and use things from your widget.

If you only plan to ever have your widget only used from its python package, there is no need to publish to npm.



> At which point, do we pull the assets from NPM and not use the bundled assets?

I'm not sure exactly what you are asking. For classic Jupyter Notebook, the dependencies will be bundled together and distributed in the python package. For JupyterLab, the dependencies will be pulled from npm when the extension is installed into jupyterlab and jupyterlab is rebuilt. This will change in jlab 3 (where it will bundle many dependencies into the python package).

**Comment by sodennis** [comment]
> I'm not sure exactly what you are asking. For classic Jupyter Notebook, the dependencies will be bundled together and distributed in the python package. For JupyterLab, the dependencies will be pulled from npm when the extension is installed into jupyterlab and jupyterlab is rebuilt. This will change in jlab 3 (where it will bundle many dependencies into the python package).

This is what I was asking about. I didn't know that JupyterLab or the HTML manager will pull the npm package. I'll try to look for more documentation around that. Thanks.
