### ISSUE TITLE
Support for Jupyter Lab 3

### ISSUE THREAD

**Issue by amirebrahimi** [jupyter-widgets/widget-cookiecutter#79]
I tested out #72 with creating a new cookiecutter to test with Jupyter Lab 3. I get the follow error when attempting to instantiate `HelloWorld()` in a jupyter notebook:

```Failed to load resource: the server responded with a status of 404 (Not Found)``` (tries to load http://localhost:8888/lab/extensions/pyQuirk/static/remoteEntry.38fd4edf763d3502e46e.js)

When Iook in my `share/jupyter/labextensions/<package>/package.json` file I see the following section under `"jupyterlab":`:
```
    "_build": {
      "load": "static\\remoteEntry.38fd4edf763d3502e46e.js",
      "extension": "./extension"
    }
```

TIA for anyone who knows how to solve this issue.

**Comment by amirebrahimi** [comment]
A bit more on this. I tried starting from scratch:
```
conda create -n jupyterlab3 python=3
conda install -c conda-forge jupyterlab3 nodejs
cookiecutter https://github.com/jupyter/widget-cookiecutter.git
cd hwjl3
pip install -e .
jupyter labextension install js
```

Then, I run `jupyter lab` create a notebook and try this code:
```
from hwjl3 import *
HelloWorld()
```
`Error displaying widget...`


This is the error I get in the console:
`:8888/static/lab/jlab_core.8356d3a981e7604d0b5b.js:92586 Plugin 'hwjl3' failed to activate.`

**Comment by martinRenou** [comment]
This should work for JupyterLab 3 now
