### ISSUE TITLE
"Not registered as widget module" error in JupyterLab

### ISSUE THREAD

**Issue by rmorshea** [jupyter-widgets/widget-cookiecutter#82]
I am experiencing the following errors in JupyterLab 3.0.5 after generating a repository from the latest version of this template:

![image](https://user-images.githubusercontent.com/4041990/104999473-c3a7cd80-59e1-11eb-84cb-b013b1031735.png)

To produce this error I created [a new branch](https://github.com/idom-team/idom-jupyter/pull/9) in my repository, deleted everything in it, and proceeded to recreated it from the latest template, only copying and pasting the relevant portions of my widget implementation.

**Comment by jasongrout** [comment]
Do you see these errors from the default cookiecutter output (i.e., without copying/pasting relevant portions of your widget implementation)?

If not, can you make two commits - one with the default output, then one with your changes to the default output?

**Comment by rmorshea** [comment]
Template without any modifications works. Will create the two commits so you can see the diff momentarily...

**Comment by rmorshea** [comment]
@jasongrout here's the diff between the generated template and my implementation:

https://github.com/idom-team/idom-jupyter/compare/d39f3318255defbc767db1c9fa8eeb6881418fdf...74321ffc6e73abab488ee47e1e8b6978fbd40906

**Comment by jasongrout** [comment]
Since the cookie cutter itself works, I'll close this. Let's continue the discussion on your PR. I've commented there about the above error.
