### ISSUE TITLE
Support for JLab 3.x ?

### ISSUE THREAD

**Issue by dou-du** [jupyter-widgets/widget-cookiecutter#83]
I try this template for JLab 3.x. It seems it is not working for JLab 3.x. Due to some importing 
problems, I can only try to use this javascript cookiecutter (the ts cookiecutter is working for me).

Does this cookiecutter supports JLab3.x ? If not, could you update for it. Thanks a lot!

**Comment by martinRenou** [comment]
The cookiecutter has been updated for JupyterLab 3 already. What is the import issue you are seing?

**Comment by dou-du** [comment]
> The cookiecutter has been updated for JupyterLab 3 already. What is the import issue you are seeing?

Thanks. I will try to check with the latest cookiecutter. For the importing problems, I try to use the widget-cookiecutter-ts.
But I do not know how to import  "**.min.js" files to the widget.ts file. Could you give some suggestions ?

**Comment by martinRenou** [comment]
> But I do not know how to import "**.min.js" files to the widget.ts file

What are you trying to do exactly? I fail to understand the question.

**Comment by dou-du** [comment]
> > But I do not know how to import "**.min.js" files to the widget.ts file
> 
> What are you trying to do exactly? I fail to understand the question.

I am sorry for the confusion. The import problem is from using the widget-cookiecutter-ts template. I will close this issue here and ask in the widget-cookiecutter-template repository.
