### ISSUE TITLE
README install instructions for Jupyter lab are unclear

### ISSUE THREAD

**Issue by willeppy** [jupyter-widgets/widget-cookiecutter#88]
Hi,

### Description

I installed this cookie cutter onto my local machine and was following the README to set up for Jupyter lab, however ran into some issues.

When I run bash`pip install -e .` it executes successfully and installs. However, when I run `jupyter labextension develop BasicWidget` I get the following error.

```bash
Installing /Users/wepperso/Documents/Research/Projects/Notebook_Vis_Rec_Projects/BasicWidget/BasicWidget/labextension -> BasicWidget
An error occured.
ValueError: /Users/wepperso/opt/anaconda3/envs/jupTest/share/jupyter/labextensions/BasicWidget exists and is not a symlink
See the log file for details:  /var/folders/zg/pzhsf9sj45qcbpm46g7m_gf80000gp/T/jupyterlab-debug-i408sjj9.log

```

The widget still seems to work however. My question is what does the `jupyter labextension develop` command do? In order to get changes in the js/ folder to show up I have to re-run `pip install -e .` so I assume it might help with this. 

Note: I did _not_ run the install instructions for Jupyter notebook beforehand, only for lab. Is this necessary for the lab install to work?

### OS
- macOS Big Sur 11.1
- Python 3.9.1
- Jupyter lab 3.0.7
- Jupyter notebook 6.2.0

**Comment by jasongrout** [comment]
Don't forget the `--overwrite` mentioned in the readme. It's complaining that there is something already there (indeed, installed by the pip install command), which it will need to overwrite with the symlink.

```
jupyter labextension develop --overwrite BasicWidget
```

**Comment by willeppy** [comment]
Got it, this worked thanks! I didn't see the --overwrite mentioned in the README currently so opened a PR to update 

#89

**Comment by jasongrout** [comment]
> I didn't see the --overwrite mentioned in the README currently so opened a PR to update

Ah, I was looking in the generated readme in the project, which does mention the --overwrite flag. Thanks for the update to the top-level readme!
