### ISSUE TITLE
single quotes vs double quotes

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/widget-cookiecutter#91]
setup.py has some weird switches between single and double quotes, sometimes in the same line. We should be consistent (probably using single quotes, since that is what is used in most of the file):

https://github.com/jupyter-widgets/widget-cookiecutter/blob/de21c0fbbcac79b4b0419097973db869da2e5550/%7B%7Bcookiecutter.github_project_name%7D%7D/setup.py#L35-L40

**Comment by 96RadhikaJadhav** [comment]
@jasongrout  Can I work on the issue?

**Comment by jasongrout** [comment]
Yes, please!
