### ISSUE TITLE
Why are the js files written in requirejs?

### ISSUE THREAD

**Issue by Naman-ntc** [jupyter-widgets/widget-cookiecutter#97]
Is there any particular reason the js files are written in the requirejs format? 
Since webpack will convert complete javascript code to AMD format the actual implementation of index.js/extension.js should not matter right. Personally, I find import/export syntax of ES6 format easier and have primarily seen that.

**Comment by dlqqq** [comment]
I think this is closed by #105. The files use ES6 imports now.
